### GENERAL SETTINGS ###

# Site settings
title: Taylor Smith.
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "taylorcsmith.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#383838" #"#F70031"
  primary_rgb: "22,22,22" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#C4610D" #"#33004D"
  link: "#222222"
  link_hover: "#474A48"
  footer_heading: "#4c4c4c"
  footer_content: "#ffffff"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url:
  - title: twitter
    url:
  - title: instagram
    url:
  - title: tumblr
    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Some Ave, 987,
    - 23890, New York,
    - United States.
email: tcs140230@utdallas.edu
tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: KensoDev
    position: Mock Interviews and Projects
    text: Self Bio - Senior SRE & Software Engineer @Globalityinc. Opinions are my own. Deal with it.
    img: kenso.jpg
    social:
      - title: twitch #use for email address
        url: https://www.twitch.tv/kensodev
      - title: twitter
        url: https://twitter.com/KensoDev
  - name: Omatum_Greg
    position: Founder at Omatum
    text: Ruby on Rails Guru and one of the founders of Omatum, he often streams content that the company is working on.
    img: greg.jpg
    social:
      - title: twitch #use for email address
        url: https://www.twitch.tv/omatum_greg
      - title: internet-explorer
        url: https://www.omatum.com/
  - name: JumpyStick
    position: Lead Developer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: jumpy.jpg
    social:
      - title: twitch #use for email address
        url: https://www.twitch.tv/jumpystick
      - title: internet-explorer
        url: http://kat.cafe/
  - name: Matthew Mckinney
    position: Boosted Monkey
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: matt.jpg
    social:
      - title: github #use for email address
        url: https://github.com/MattMcKinney
      - title: internet-explorer
        url: https://matthew-mckinney.com/

# Clients information. Shown on Home and About pages.
clients:
  - name: Kata
    img: katalogo.png
  - name: Fullstack
    img: FSSymbol.png
  - name: Omatum
    img: omatum.jpg
  - name: VimeoPro
    img: client04.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "Wubba lubba dub-dub!"
    author: Rick Sanchez
    position: TINKERER OF TERROR - HIMSELF
