### GENERAL SETTINGS ###

# Site settings
title: Taylor Smith.
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "taylorcsmith.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#383838" #"#F70031"
  primary_rgb: "22,22,22" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#C4610D" #"#33004D"
  link: "#222222"
  link_hover: "#474A48"
  footer_heading: "#4c4c4c"
  footer_content: "#ffffff"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/TaylorCSmith
  - title: linkedin
    url: https://www.linkedin.com/in/taylorcodysmith/
  - title: twitch
    url: https://www.twitch.tv/terrifictaylor
  - title: code
    url: https://www.hackerrank.com/taylor_cody_smi1
  - title: cog
    url: https://www.codewars.com/users/TaylorCSmith

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Dallas, Texas
    - United States.
email: tcs140230@utdallas.edu


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: KensoDev
    position: Mock Interviews and Projects
    text: Self Bio - Senior SRE & Software Engineer @Globalityinc. Opinions are my own. Deal with it.
    img: kenso.jpg
    social:
      - title: twitch #use for email address
        url: https://www.twitch.tv/kensodev
      - title: twitter
        url: https://twitter.com/KensoDev
  - name: Omatum_Greg
    position: Founder at Omatum
    text: Ruby on Rails Guru and one of the founders of Omatum, he often streams content that the company is working on.
    img: greg.jpg
    social:
      - title: twitch #use for email address
        url: https://www.twitch.tv/omatum_greg
      - title: internet-explorer
        url: https://www.omatum.com/
  - name: JumpyStick
    position: Lead Developer
    text: Has a great stream on twitch that is rapidly growing. Really helpful if you ask her for advice on stream or her discord.
    img: jumpy.jpg
    social:
      - title: twitch #use for email address
        url: https://www.twitch.tv/jumpystick
      - title: internet-explorer
        url: http://kat.cafe/
  - name: Matthew Mckinney
    position: Boosted Monkey
    text: Guy who originally pushed me into C# and software and gave me a ton of resources for learning. His site has a lot of resources.
    img: matt2.jpg
    social:
      - title: github #use for email address
        url: https://github.com/MattMcKinney
      - title: internet-explorer
        url: https://matthew-mckinney.com/

# Clients information. Shown on Home and About pages.
clients:
  - name: Kata
    img: katalogo.png
  - name: Fullstack
    img: FSSymbol.png
  - name: Omatum
    img: omatum.jpg
  - name: VimeoPro
    img: client04.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Just an Electrical Engineering graduate trying to find his way in the world of software :)"

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "Let me reiterate: I'm talking about software. Hardware rules, in my experience, tend to actually be yes-we-mean-it rules. That's pretty much why I got out of electrical engineering and into software."
    author: <font color="white">Jon Evans</font>
    position: Novelist, Journalist, and Software Engineer
